export const LOAD_CATS_SUCCESS = 'LOAD_CATS_SUCCESS';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const LOAD_POSTS_SUCCESS = 'LOAD_POSTS_SUCCESS';
export const LOAD_DETAIL_POST_SUCCESS = 'LOAD_DETAIL_POST_SUCCESS';
export const LOAD_POST_COMMENTS_SUCCESS = 'LOAD_POST_COMMENTS_SUCCESS';
